Windows support
fnep/mtv_dl pull request #7
Opened 2020-03-04 04:07 UTC by Dobatymo

Hi, this pull request would enable Windows support.

The following 3 things were necessary to make it work:

- remove the file locking as `fcntl` does not exist on Windows
- close the temporary file prior to removal as Windows would complain otherwise
- replace more characters in filenames like `<>:"/\\|?*` and ASCII control chars

The other changes are minor and not Windows specific.

2020-03-04 07:58 UTC, efenka commented
In general, I would welcome windows support, but honestly your pull requests changes a lot more than needed for windows support. 

I'm not so happy with all the changes, so I will add some comments to the diff to discuss this further.

2020-03-04 08:21 UTC, fnep requested changes
My comments seem to be very pedantic, so please don't get me wrong. I like the change, but I think here is a lot about personal preferences and about the actual change.

2020-03-04 08:21 UTC, fnep commented on mtv_dl.py
> +LIMIT_DESC = 40
This is not related to windows. If you want such a feature, put it in a separate request.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +system = platform.system()
This variable is only used once. Please use platform.system() directly.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +from itertools import chain, islice
Please import only one module per line (same for timezone). This to simplify merges.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +            except Exception as e:
`e` is unsued.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +                        logger.debug("Saving cache to %s.", _cache_file)
Why not `%r`? I like to see the repr in the logs.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +                        logger.debug("Using cache from %s.", _cache_file)
Why not `%r`?

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +                logger.debug('Opening database from %s.', url)
`%r`

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +invalidre = re.compile("[{}]".format(re.escape(invalid_chars)))
To make clear this is a constant, please use uppercase and underscore naming.

I also see no good reason to use re.escape here: Better the compiled regex in the if-else above.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +            with lzma.open(showlist_path, 'rt', encoding='utf-8') as fh:
This is a nice change. I did not know it existed.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +            logger.debug('Downloading %s from %s.', self.label, show_url)
`%r` please.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +                logger.debug('Downloading subtitles for %s from %s.', self.label, self['url_subtitles'])
`%r` please.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +            logger.warning('Skipped %s. Moving %s to %s failed: %s', self.label, source_path, destination_file_path, e)
`%r` please.

2020-03-04 08:21 UTC, efenka commented on mtv_dl.py
> +            logger.debug("Dropped cache %s.", self.cache_file_path)
`%r` please.

2020-03-05 02:49 UTC, Dobatymo commented
Thanks for your feedback. I should have limited the PR to Windows support in the first place. I think I have fixed all your comments except the one regarding `re.escape`. Why is it not necessary?

While debugging I was annoyed by all the WindowsPath(asd/asd) stuff instead of only 'asd/asd'. That's why I left the `%s` in the code before.

2020-03-05 06:28 UTC, efenka commented
I had another look and think its fine now.  👍

Thanks a lot for you work!

--- 

I have no time these days to publish it as a new release, but i will do so as soon as possible. I also thought about using sqlite instead of pickle to cache the Filmliste file. This way we would also avoid the locking issues in future and propably its even faster. But i need a little bit mor time to test this idea.

2020-03-05 06:28 UTC, merged